# LIST:-
#      Is a linear combination of data items also knwom as List Items.
#      Ex- list of marks (13,22,8,7,19)

# NODE:
      #  - A node is a container that holds data and one or more links/pointers to other nodes.

class Node:
    def __init__(self,item = None,next = None):
        self.item = item
        self.next = next

# SINGLY LINKED LIST:
              #   Singly linkd list is a linear data structure.
              # It can grow and shrink.
              # It is known as singly linked because each node has single linked with next node.

# OPERATIONS ON SLL:

# 1.) Insertion
# 2.) Deletion
# 3.) Is_empty
# 4.) traverse


